const FILTER_DEFAULTS = {
  PRICING_DEFAULT_CURRENCY: 'EUR',
  LISTING_PRICE_FILTER_MAX: 500,
  LISTING_PRICE_FILTER_MIN: 0,
  LISTING_PRICE_FILTER_STEP: 10,
  LISTING_RANGE_FILTER_MIN: 50,
  LISTING_RANGE_FILTER_MAX: 8000,
  LISTING_RANGE_FILTER_STEP: 50,
  LISTING_RANGE_FILTER_DEFAULT_VALUE: 2000
};

export default FILTER_DEFAULTS;